{
 "title": "Test Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by(cpu) (irate(node_cpu_seconds_total{job=\"node-exporter\", mode!=\"idle\"}[$__rate_interval]))) *100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Percentage Used",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "100 - (($B/$A)*100)", "type": "math" }
   ]
  },
  {
   "title": "Ram usage (MB)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes / 1024 / 1024",
     "legendFormat": "Memory Free"
    },
    { "expression": "$A - $B", "type": "math" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Request count by path",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "by_path_counter_total{path!=\"/metrics\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request count by type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "flask_http_request_total{}", "legendFormat": "{{method}}" }
   ]
  }
 ]
}